const userData = require("../controller/userController")
const express = require("express")
const app = express.Router()
const passport = require("passport")
const middleware = require("../middleware")
app.post("/addData", userData.addData)
app.get("/fetchData", userData.fetchData)
app.post("/checkData", userData.checkUserData)
app.post("/changeStatus", middleware, userData.changeStatus)
app.delete("/deleteUser", middleware, userData.deleteUser)
app.get("/editData", middleware, userData.editUser)
app.post("/updateData", middleware, userData.updateUser)
// app.get("/google", userData.google)
// app.get("google/callback", userData.googleCallback)
module.exports = app
